//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlinemxc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_boxingscan_h
    {
        public Nullable<System.DateTime> fecha { get; set; }
        public string linea { get; set; }
        public Nullable<int> hora { get; set; }
        public Nullable<decimal> cajas { get; set; }
        public Nullable<int> kits { get; set; }
        public Nullable<int> wos { get; set; }
        public Nullable<int> tmuerto { get; set; }
        public string horaformato { get; set; }
    }
}
