//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlinemxc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_boxingscan
    {
        public int folio { get; set; }
        public string lote { get; set; }
        public string wo { get; set; }
        public string pn { get; set; }
        public Nullable<int> cajas_total { get; set; }
        public Nullable<decimal> cajas_scan { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string linea { get; set; }
        public Nullable<int> tmuerto { get; set; }
    }
}
