//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlinemxc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_boxingscan_cambiowo
    {
        public int folio { get; set; }
        public string linea { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string wo_anterior { get; set; }
        public string wo_nueva { get; set; }
        public Nullable<int> bloqueo { get; set; }
    }
}
