//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlinemxc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_config
    {
        public string clave { get; set; }
        public Nullable<decimal> jornada { get; set; }
        public Nullable<decimal> hrs_disp { get; set; }
        public Nullable<decimal> seg_disp { get; set; }
        public Nullable<decimal> cajas_linea { get; set; }
        public Nullable<decimal> kits_caja { get; set; }
        public Nullable<decimal> kits_linea { get; set; }
        public Nullable<decimal> tak_time { get; set; }
        public Nullable<decimal> tak80 { get; set; }
        public Nullable<decimal> assy_time { get; set; }
        public Nullable<decimal> max_comp { get; set; }
        public Nullable<decimal> mesa_ens { get; set; }
        public Nullable<decimal> mesa_wrap { get; set; }
        public Nullable<decimal> mesa_sub { get; set; }
        public Nullable<decimal> oper_na { get; set; }
        public Nullable<decimal> surtidor { get; set; }
        public Nullable<decimal> insp_sella { get; set; }
        public Nullable<decimal> sellador { get; set; }
        public Nullable<decimal> inspeccion { get; set; }
        public string u_id { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
        public Nullable<decimal> horizontal { get; set; }
        public Nullable<decimal> vertical { get; set; }
        public Nullable<decimal> sobre { get; set; }
        public Nullable<decimal> wrap_na { get; set; }
        public Nullable<decimal> tucktape { get; set; }
        public string version { get; set; }
        public string lenguage { get; set; }
        public Nullable<decimal> detroit { get; set; }
        public Nullable<decimal> max_hc { get; set; }
        public Nullable<decimal> min_hc { get; set; }
        public string ind_boxhr { get; set; }
        public Nullable<decimal> out_addtime { get; set; }
        public string cycle_timer { get; set; }
        public string active { get; set; }
        public Nullable<decimal> comp_pre { get; set; }
        public Nullable<int> threshold_boxscan { get; set; }
        public Nullable<decimal> factor_kitsxcaja { get; set; }
    }
}
