//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlinemxc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_lineconf
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t_lineconf()
        {
            this.t_lineconfd = new HashSet<t_lineconfd>();
            this.t_lineconfh = new HashSet<t_lineconfh>();
        }
    
        public string clave { get; set; }
        public string descrip { get; set; }
        public Nullable<decimal> meta { get; set; }
        public string meta_um { get; set; }
        public string turno { get; set; }
        public string u_id { get; set; }
        public Nullable<System.DateTime> f_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_lineconfd> t_lineconfd { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<t_lineconfh> t_lineconfh { get; set; }
    }
}
