//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace medlinemxc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_tmuerto_razon_por_linea_wo
    {
        public string linea { get; set; }
        public string wo { get; set; }
        public string fecha { get; set; }
        public string tmuerto_razon { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> tiempo_muerto { get; set; }
    }
}
